### ISSUE TITLE
-Werror=unused-variable and -Werror=unused-parameter

### ISSUE THREAD

**Issue by gtianyi** [gtianyi/SituatedSIPP#16]
https://github.com/gtianyi/SituatedSIPP/blob/fabe5c59bf6dd5da3227ce8adcba3fcc008ab3a3/src/situatedSIPP/learningAlgorithms/DijkstraLearning.cpp#L25

https://github.com/gtianyi/SituatedSIPP/blob/fabe5c59bf6dd5da3227ce8adcba3fcc008ab3a3/src/situatedSIPP/learningAlgorithms/learningAlgorithmBase.cpp#L26

I got 2 compile errors on these two lines during release mode compilation. I thought we are using the same compile flag so this error should also show up on your side? 

If not, we have to find the inconsistency on the setup. 
If yes, next time before submitting a pull request, please make sure it compiles on both release and debug mode.

**Comment by dwthomas** [comment]
I did not check it compiled on release, I'll be sure to do that moving forward.
